-- phpMyAdmin SQL Dump
-- version 4.0.10.10
-- http://www.phpmyadmin.net
--
-- Хост: 127.0.0.1:3306
-- Время создания: Фев 14 2017 г., 20:35
-- Версия сервера: 5.6.26
-- Версия PHP: 5.5.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- База данных: `book2`
--

-- --------------------------------------------------------

--
-- Структура таблицы `theatre`
--

CREATE TABLE IF NOT EXISTS `theatre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `orig_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=50 ;

--
-- Дамп данных таблицы `theatre`
--

INSERT INTO `theatre` (`id`, `name`, `description`, `image`, `orig_url`) VALUES
(1, 'Театр Et Cetera', 'Театр Калягина, или, как настаивает сам Александр Александрович, театр Et Cetera, театр с именем, которое выбрали ему с большой любовью и тщательно.\r\nТеатр бесконечен в своем развитии, в своих изысканиях, в своих устремлениях.\r\nТеатр Калягина никогда не с', 'https://msk.kassir.ru/media/poster/40eaaf85ea5c7cee9b97792859b72be5.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-et-cetera","name":"Театр Et Cetera - Эфросовский зал","address":"Москва, Фролов пер., 2', 'https://msk.kassir.ru/kassir/hall/view/307519'),
(2, 'Театр им. К.С.Станиславского и Вл.И.Немировича-Данченко (МАМТ)', 'Московский академический Музыкальный театр им. К.С. Станиславского и Вл.И. Немировича­-Данченко находится в историческом здании на Большой Дмитровке. После масштабной реконструкции 2003-2006 гг. театр стал один из самых современных театральных комплексов ', 'https://msk.kassir.ru/media/poster/7c08a16469b5a70029da6b807a79b45b.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-ksstanislavskogo-i-vlinemirovicha-danchenko","name":"Театр им. Станиславского и Немировича (МАМТ) - Малая', 'https://msk.kassir.ru/kassir/hall/view/290790'),
(3, 'Театр «Русская песня»', 'Вы можете купить билет на мероприятие в &quot;Театр Русской песни&quot; в кассах Кассира в городе Москва или на сайте. После оплаты электронный билет будет выслан на ваш электронный адрес. Также вы можете купить билеты в другие залы Москвы.\r\nКассир.ру — н', 'https://msk.kassir.ru/media/poster/e4a80ea9a68f0dc8cc6f581d15c1751b.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-russkaya-pesnya","name":"Театр «Русская песня»","address":"Москва, Олимпийский пр.,14', 'https://msk.kassir.ru/kassir/hall/view/46389'),
(4, 'Московский театр п/р О.Табакова', 'Билеты в Театр Табакова охотно приобретают не только в России, но и за рубежом. Коллектив «Табакерки» выезжает на гастроли ежемесячно, выступает в США, Канаде, странах Европы. Режиссеры-постановщики — сам Олег Павлович, а также Владимир Машков, Александр ', 'https://msk.kassir.ru/media/poster/a9d663dbfd0301238423201383439010.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/moskovskiy-teatr-pr-otabakova","name":"Театр Табакова — приходите в «Табакерку»!","address":"Москва, ул. Чаплыгина', 'https://msk.kassir.ru/kassir/hall/view/290187'),
(5, 'Государственный центр-музей В.С.Высоцкого', 'Сотрудники Музея проводят экскурсии, читают тематические лекции,\r\nорганизуют концерты, викторины для детей, фестивали молодых талантов.\r\nГКЦМ активно работает со школами и колледжами, домами-интернатами,\r\nсотрудничает с многочисленными клубами, частными м', 'https://msk.kassir.ru/media/poster/37c0c9ff1717c59c30988821fb38f73d.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/muzei/gosudarstvennyiy-tsentr-muzey-vsvyisotskogo","name":"Театрально-концертный зал Дом Высоцкого","address":"г.Москва, ', 'https://msk.kassir.ru/kassir/hall/view/51954'),
(6, 'Театр Аллы Духовой «TODES»', 'Вы можете купить билет на мероприятие в &quot;Театр Аллы Духовой «TODES»&quot; в кассах Кассира в городе Москва или на сайте. После оплаты электронный билет будет выслан на ваш электронный адрес. Также вы можете купить билеты в другие залы Москвы.\r\nКассир', 'https://msk.kassir.ru/media/poster/be7f31ba5a2bf039e92b54d3b0855e56.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-allyi-duhovoy-todes","name":"Театр Аллы Духовой «TODES»","address":"г. Москва, Проспект Мира, д. 95, стр.1', 'https://msk.kassir.ru/kassir/hall/view/55683'),
(7, 'ДК им. Зуева', 'Купить билет на понравившееся мероприятие в &quot;ДК им. Зуева&quot; можно онлайн на сайте или кассах Кассира в городе Москва. При покупке онлайн вы получаете электронный билет на e-mail сразу после оплаты.\r\nТакже вы можете посмотреть, какие события прохо', 'https://msk.kassir.ru/media/poster/278eee2b0ac84875bf256d48eb3360c2.png","location":{"@type":"Place","url":"https://msk.kassir.ru:443/doma-kultury/dk-im-zueva","name":"ДК им. Зуева","address":"Москва, ул. Лесная д.18', 'https://msk.kassir.ru/kassir/hall/view/29120'),
(8, 'Театральный центр «На Страстном»', 'Театральный центр СТД РФ (ВТО) «На Страстном», расположенный\r\nпо соседству с основным зданием Союза театральных деятелей по адресу\r\nСтрастной бульвар, 8а, —  уникальная площадка. Это первая по-настоящему открытая\r\nсцена в Москве, о необходимости которой т', 'https://msk.kassir.ru/media/poster/36d65680272856b6f200743806dd96da.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatralnyiy-tsentr-na-strastnom","name":"Театральный центр «На Страстном»","address":"г.Москва, Страстной б-р, д. ', 'https://msk.kassir.ru/kassir/hall/view/24256'),
(9, 'Театр Содружество Актеров Таганки', 'В 1993 году театр был создан после раскола Театра на Таганке надвое. Художественным руководителем Содружества стал Народный артист России Николай Губенко . Театр всегда был полон творческой энергии и новых идей. Даже тогда,\r\nкогда не было самых необходимы', 'https://msk.kassir.ru/media/poster/d5f6b92583727e4888f1e0e5687734a8.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-sodrujestvo-akterov-taganki","name":"Содружество Актеров Таганки","address":"Москва, ул. Земляной вал, д. 76', 'https://msk.kassir.ru/kassir/hall/view/28772'),
(10, 'Московский театр п/р О.Табакова', 'Билеты в Театр Табакова охотно приобретают не только в России, но и за рубежом. Коллектив «Табакерки» выезжает на гастроли ежемесячно, выступает в США, Канаде, странах Европы. Режиссеры-постановщики — сам Олег Павлович, а также Владимир Машков, Александр ', 'https://msk.kassir.ru/media/poster/a9d663dbfd0301238423201383439010.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/moskovskiy-teatr-pr-otabakova","name":"Театр Табакова — приходите в «Табакерку»!","address":"Москва, ул. Чаплыгина', 'https://msk.kassir.ru/kassir/hall/view/307356'),
(11, 'Театр Эстрады', 'На сайте КАССИР.РУ жители и гости столицы могут забронировать либо купить билеты онлайн в Театр эстрады. Информация о наличии свободных мест и их стоимости доступна в любое время суток.\r\nАфишу Московского государственного театра эстрады составляют концерт', 'https://msk.kassir.ru/media/poster/fd92cad4f9761332ffe7607e647af952.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-estradyi","name":"Театр Эстрады - Основная сцена","address":"г.Москва, Берсеневская наб., 20/2', 'https://msk.kassir.ru/kassir/hall/view/24046'),
(12, 'Государственный Московский Мюзик-Холл', 'Купить билеты на лучшие танцевальные постановки, шоу, концертные программы в «Государственный Московский Мюзик-Холл» вы можете в любое время в кассах или на сайте КАССИР.РУ. У нас также представлены предложения от концертных залов и театров со всей России', 'https://msk.kassir.ru/media/poster/e4ff6c868eab33615f95a12339dbdfac.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/koncertnye-zaly/gosudarstvennyiy-moskovskiy-myuzik-holl","name":"«Государственный Московский Мюзик-Холл»","address":"Моск', 'https://msk.kassir.ru/kassir/hall/view/28306'),
(13, 'Театр «Современник»', '', 'https://msk.kassir.ru/media/poster/e5ba55d2001f001385bec6610c029893.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-sovremennik","name":"Московский театр "СОВРЕМЕННИК" (ТКЗ "Дворец на Яузе")","address":"г.Москва, пл. Журавлё', 'https://msk.kassir.ru/kassir/hall/view/290027'),
(14, 'Театр Музыки и Драмы п/р Стаса Намина', 'Театр музыки и драмы Стаса Намина в Москве знаменит своими новаторскими постановками. Основу репертуара составляют музыкальные спектакли и перформансы. Известные режиссеры и талантливая труппа создают на основе традиционных мюзиклов глубокие драматические', 'https://msk.kassir.ru/media/poster/89410f5d54835fdee49de9705f0a4f02.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-muzyiki-i-dramyi-pr-stasa-namina","name":"Театр Стаса Намина","address":"Москва, Крымский Вал, д. 9, стр. 33', 'https://msk.kassir.ru/kassir/hall/view/28940'),
(15, 'Театр Наций', 'Театр Наций расположен в здании крупнейшего в России частного драматического театра, открытого Фёдором Коршем в 1885 году. За 130 лет существования здания здесь произошло множество важных для истории театрального искусства событий, театр несколько раз мен', 'https://msk.kassir.ru/media/poster/caad403c7e147dd1e5a31cf94d866612.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-natsiy","name":"Театр Наций - Большой зал","address":"Москва, Петровский пер., 3', 'https://msk.kassir.ru/kassir/hall/view/23931'),
(16, 'Театр на Малой Бронной', 'ВНИМАНИЕ! На спектакли Театра на Малой Бронной за 72 часа до начала срок бронирования билетов сокращается до 15 минут!\r\nКАССИР.РУ предлагает вам ознакомиться с афишей Московского драматического театра на Малой Бронной и приобрести билеты на любой спектакл', 'https://msk.kassir.ru/media/poster/38ca8d29038207956cc47e05b0036371.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-na-maloy-bronnoy","name":"Театр на Малой Бронной - Малый зал","address":"Москва, Малая Бронная, 4', 'https://msk.kassir.ru/kassir/hall/view/24031'),
(17, 'ЦКИ "Меридиан"', 'Вы можете купить билет на мероприятие в &quot;ЦКИ &quot;Меридиан&quot; - Большой зал&quot; в кассах Кассира в городе Москва или на сайте. После оплаты электронный билет будет выслан на ваш электронный адрес. Также вы можете купить билеты в другие залы Мос', 'https://msk.kassir.ru/media/poster/425a12201610faecf58b67d9d79c8a86.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/doma-kultury/tski-meridian","name":"ЦКИ "Меридиан" - Большой зал","address":"Москва, ул. Профсоюзная, д. 61', 'https://msk.kassir.ru/kassir/hall/view/28725'),
(18, 'Театр Оперетты', 'На сцене театра оперетты каждый сезон срывают аншлаги 300 спектаклей, которые посещает полмиллиона зрителей. Если хотите увидеть постановку в Москве, приобретайте билеты на КАССИР.РУ.\r\nТеатр оперетты был основан знаменитым актером и режиссером Григорием Я', 'https://msk.kassir.ru/media/poster/33742203fee0b5f6d21bce74a64ad5d8.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-operettyi","name":"Театр Оперетты (Основная сцена)","address":"г. Москва, Большая Дмитровка, 6', 'https://msk.kassir.ru/kassir/hall/view/290019'),
(19, 'Электротеатр Станиславский', 'Электротеатр Станиславский – это комплексная творческая территория, центром которой является обновленный театр им. Станиславского. Театр расположен на главной улице Москвы, по адресу Тверская, 23. С 1915 года здесь находился популярный кинозал Электротеат', 'https://msk.kassir.ru/media/poster/0a2288328105c44d4b01c0214f23cf8c.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/elektroteatr-stanislavskiy","name":"Электротеатр Станиславский - Малая сцена","address":"Москва, ул. Тверская, 23', 'https://msk.kassir.ru/kassir/hall/view/307007'),
(20, 'Театр Сатирикон', 'На сайте КАССИР.РУ вы всегда можете купить либо забронировать билеты в театр «Сатирикон». Это спектакли постоянного репертуара, моноспектакли-концерты, постановки гастролирующих коллективов. Благодаря отличному сервису оформление и получение заказа удобно', 'https://msk.kassir.ru/media/poster/f413ceb4141caa30ee241164f3729b52.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-satirikon","name":"Театр Сатирикон на сцене ММЦ «Планета КВН»","address":"Москва, ул. Шереметьевская, д.2', 'https://msk.kassir.ru/kassir/hall/view/290112'),
(21, 'Театр им. Моссовета', 'КАССИР.РУ предлагает вам выбрать и купить билеты в театр им. Моссовета в любое удобное время. Вся информация, представленная в афише, регулярно обновляется. Это позволяет нашим пользователям заблаговременно узнавать об изменениях и иметь возможность плани', 'https://msk.kassir.ru/media/poster/6ac1e976348d3ee3bef240e9fcab572a.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-mossoveta","name":"Театр им. Моссовета","address":"Москва, Б. Садовая, 16. Сад', 'https://msk.kassir.ru/kassir/hall/view/24216'),
(22, 'Театрально-концертный зал ЦДКЖ', 'Именно ЦДКЖ продавал билеты на спектакли под руководством А. В. Александрова и сольные концерты Леонида Утесова, оперетты Иосифа Дунаевского. Само здание — памятник истории. В настоящий момент здесь проходят конкуры и награждения, юбилеи и презентации, пр', 'https://msk.kassir.ru/media/poster/25dc60a204cca12a5b41cd5dfcc0eec2.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatralno-kontsertnyiy-zal-tsdkj","name":"Театрально-концертный зал ЦДКЖ - Большой зал","address":"Москва, Комсомо', 'https://msk.kassir.ru/kassir/hall/view/24255'),
(23, 'Театр им. Н.И. Сац', 'Театр имени Наталии Сац — это настоящий детский театр, так что будьте готовы к\r\nоглушительному гвалту в фойе, к сладкой вате и к тому, что оркестр\r\nнемного не в форме. Здесь, как в наглядном пособии для музыкальной\r\nшколы, всегда давали пристойные перелож', 'https://msk.kassir.ru/media/poster/ccbb37e64166c9b18e2f5d2522961ea0.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-ni-sats","name":"Театр им. Н.И. Сац - Малая сцена","address":"г. Москва, Проспект Вернадского, 5', 'https://msk.kassir.ru/kassir/hall/view/24037'),
(24, 'МХТ им. А.П.Чехова', 'С момента своего основания в 1987 году МХТ им. Чехова является знаковым местом для любителей театрального искусства. Посетите этот театр с КАССИР.РУ!\r\nС 2000 года художественным руководителем является Олег Табаков. В труппе свыше 20 народных и 30 заслужен', 'https://msk.kassir.ru/media/poster/7418736dd93334f6d9fdc98eda92b02a.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/mht-im-apchehova","name":"МХТ им. А.П.Чехова - Новая сцена","address":"г. Москва, Камергерский пер., д. 3', 'https://msk.kassir.ru/kassir/hall/view/39641'),
(25, 'ГАУК МО "Московский Губернский театр"', 'Московский Губернский драматический театр начал свое\r\nсуществование в 2013 году. Он создан путем слияния двух областных\r\nтеатров: Московского областного драматического театра им.\r\nА.Н.Островского и Московского областного государственного Камерного\r\nтеатра', 'https://msk.kassir.ru/media/poster/ac539cf03b84f490035688048f95623c.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/gauk-mo-moskovskiy-gubernskiy-teatr","name":"ГАУК МО "Московский Губернский театр" - Малый зал","address":"г. Моск', 'https://msk.kassir.ru/kassir/hall/view/29196'),
(26, 'Театр им. Евг. Вахтангова', 'На сайте КАССИР.РУ вы всегда можете купить или забронировать билеты в Театр им. Вахтангова. Сервис доступен круглосуточно, без выходных, а оформление заказа займет всего пару минут.\r\nЛегендарный Театр им. Вахтангова неизменно входит в тройку лучших театра', 'https://msk.kassir.ru/media/poster/27429ae4ea566527ad3f52cafc0d02ae.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-evg-vahtangova","name":"Театр им. Евг. Вахтангова - Основная сцена","address":"г. Москва, ул. Арбат, д. 2', 'https://msk.kassir.ru/kassir/hall/view/29025'),
(27, 'Центральный Дом работников искусств (ЦДРИ)', 'Купить билет на понравившееся мероприятие в &quot;Центральный Дом работников искусств (ЦДРИ) - Большой зал&quot; можно онлайн на сайте или кассах Кассира в городе Москва. При покупке онлайн вы получаете электронный билет на e-mail сразу после оплаты.\r\nТак', 'https://msk.kassir.ru/media/poster/38fe9a2f5f6378e5fedc1f60d63f4868.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/doma-kultury/tsentralnyiy-dom-rabotnikov-iskusstv-tsdri","name":"Центральный Дом работников искусств (ЦДРИ) - Большой зал', 'https://msk.kassir.ru/kassir/hall/view/28955'),
(28, 'Российская государственная детская библиотека', 'Купить билет на понравившееся мероприятие в &quot;Российская государственная детская библиотека&quot; можно онлайн на сайте или кассах Кассира в городе Москва. При покупке онлайн вы получаете электронный билет на e-mail сразу после оплаты.\r\nТакже вы может', 'https://msk.kassir.ru/media/poster/03bf11d045fe702f96461b69dbea6bcd.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/biblioteki/rossiyskaya-gosudarstvennaya-detskaya-biblioteka","name":"Российская государственная детская библиотека","addr', 'https://msk.kassir.ru/kassir/hall/view/55104'),
(29, 'Театр «Эрмитаж»', '', 'https://msk.kassir.ru/media/poster/cf5d3b453caa2ca523c1b796110b4256.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-ermitaj","name":"Театр «Эрмитаж» - Зал на Арбате","address":"Москва, ул. Новый Арбат, 11', 'https://msk.kassir.ru/kassir/hall/view/306432'),
(30, 'КЦ «Москвич»', 'Вы можете купить билет на мероприятие в &quot;КЦ &quot;Москвич&quot;&quot; в кассах Кассира в городе Москва или на сайте. После оплаты электронный билет будет выслан на ваш электронный адрес. Также вы можете купить билеты в другие залы Москвы.\r\nКассир.ру ', 'https://msk.kassir.ru/media/poster/72d41758f963411600fd27be515509c4.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/doma-kultury/kts-moskvich","name":"КЦ «Москвич»","address":"Москва, Волгоградский проспект, д. 46/15', 'https://msk.kassir.ru/kassir/hall/view/28919'),
(31, 'Московский театр п/р О.Табакова', 'Билеты в Театр Табакова охотно приобретают не только в России, но и за рубежом. Коллектив «Табакерки» выезжает на гастроли ежемесячно, выступает в США, Канаде, странах Европы. Режиссеры-постановщики — сам Олег Павлович, а также Владимир Машков, Александр ', 'https://msk.kassir.ru/media/poster/a9d663dbfd0301238423201383439010.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/moskovskiy-teatr-pr-otabakova","name":"Театр Табакова — приходите в «Табакерку»!","address":"Москва, ул. Чаплыгина', 'https://msk.kassir.ru/kassir/hall/view/290188'),
(32, 'Театр «Современник»', '', 'https://msk.kassir.ru/media/poster/e5ba55d2001f001385bec6610c029893.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-sovremennik","name":"Московский театр "СОВРЕМЕННИК" (ТКЗ "Дворец на Яузе")","address":"г.Москва, пл. Журавлё', 'https://msk.kassir.ru/kassir/hall/view/290021'),
(33, 'Российский академический молодежный театр (РАМТ)', 'Основанный в 1921 году как детский театр, в 1992 году он превратился в РАМТ. Сегодня в репертуаре есть спектакли различных жанров для любых возрастных категорий.\r\nС 1980 года театр возглавляет А.В. Бородин. За это время произошел переход к более широкому ', 'https://msk.kassir.ru/media/poster/9d22769b87f5552fc4c9c2d4d55dd653.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/rossiyskiy-akademicheskiy-molodejnyiy-teatr-ramt","name":"РАМТ","address":"Москва, Театральная пл, д. 2', 'https://msk.kassir.ru/kassir/hall/view/28979'),
(34, 'Электротеатр Станиславский', 'Электротеатр Станиславский – это комплексная творческая территория, центром которой является обновленный театр им. Станиславского. Театр расположен на главной улице Москвы, по адресу Тверская, 23. С 1915 года здесь находился популярный кинозал Электротеат', 'https://msk.kassir.ru/media/poster/0a2288328105c44d4b01c0214f23cf8c.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/elektroteatr-stanislavskiy","name":"Электротеатр Станиславский - Малая сцена","address":"Москва, ул. Тверская, 23', 'https://msk.kassir.ru/kassir/hall/view/307330'),
(35, 'Центральный Дом Журналиста (ЦДЖ)', 'Вы можете купить билет на мероприятие в &quot;Центральный Дом Журналиста - Основная сцена&quot; в кассах Кассира в городе Москва или на сайте. После оплаты электронный билет будет выслан на ваш электронный адрес. Также вы можете купить билеты в другие зал', 'https://msk.kassir.ru/media/poster/f255535db31e3590726f490e32640d5d.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/doma-kultury/tsentralnyiy-dom-jurnalista-tsdj","name":"Центральный Дом Журналиста - Малый зал","address":"г. Москва, Ники', 'https://msk.kassir.ru/kassir/hall/view/308107'),
(36, 'Театр Российской Армии', 'На сайте КАССИР.РУ вы можете ознакомиться с актуальной афишей Театра Российской Армии. Свежая информация о наличии свободных мест и ценах доступна круглосуточно с любого устройства. Чтобы забронировать или купить билеты, потребуется всего пара минут.\r\nТеа', 'https://msk.kassir.ru/media/poster/06cf4adaa3d0efb3426f3c7c7187900e.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-rossiyskoy-armii","name":"Театр Российской Армии","address":"Москва, Суворовская пл., 2', 'https://msk.kassir.ru/kassir/hall/view/29681'),
(37, 'МХТ им. А.П.Чехова', 'С момента своего основания в 1987 году МХТ им. Чехова является знаковым местом для любителей театрального искусства. Посетите этот театр с КАССИР.РУ!\r\nС 2000 года художественным руководителем является Олег Табаков. В труппе свыше 20 народных и 30 заслужен', 'https://msk.kassir.ru/media/poster/7418736dd93334f6d9fdc98eda92b02a.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/mht-im-apchehova","name":"МХТ им. А.П.Чехова - Новая сцена","address":"г. Москва, Камергерский пер., д. 3', 'https://msk.kassir.ru/kassir/hall/view/81381'),
(38, 'Московский Театр Юного Зрителя (МТЮЗ)', 'Сегодня в постановках МТЮЗ задействуются лучшие актеры, а за премьерами следят во всем мире. На сайте КАССИР.РУ вы сможете купить билеты в этот театр.\r\nДо 1987 года судьба театра не отличалась от многих других советских ТЮЗов: репертуар был жестко огранич', 'https://msk.kassir.ru/media/poster/b310d1303cbf772d2baaae60c939570d.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-yunogo-zritelya-mtyuz","name":"Московский Театр Юного Зрителя (МТЮЗ)","address":"г.Москва, Мамоновский пер.,', 'https://msk.kassir.ru/kassir/hall/view/54351'),
(39, 'Театр им. Евг. Вахтангова', 'На сайте КАССИР.РУ вы всегда можете купить или забронировать билеты в Театр им. Вахтангова. Сервис доступен круглосуточно, без выходных, а оформление заказа займет всего пару минут.\r\nЛегендарный Театр им. Вахтангова неизменно входит в тройку лучших театра', 'https://msk.kassir.ru/media/poster/27429ae4ea566527ad3f52cafc0d02ae.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-evg-vahtangova","name":"Театр им. Евг. Вахтангова - Основная сцена","address":"г. Москва, ул. Арбат, д. 2', 'https://msk.kassir.ru/kassir/hall/view/307130'),
(40, 'Театриум на Серпуховке п/р Терезы Дуровой', '«Театриум на Серпуховке» ежегодно продает билеты на 15 и более спектаклей. Его идейный вдохновитель и руководитель — Тереза Дурова, представительница цирковой династии Дуровых. Тереза Ганнибаловна объединила артистов жанра клоунады в репертуарном театре, ', 'https://msk.kassir.ru/media/poster/23fdc7aa39effecf1f4635afe8417b0f.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatrium-na-serpuhovke-pr-terezyi-durovoy","name":"Театриум на Серпуховке п/р Терезы Дуровой - Основная сцена","ad', 'https://msk.kassir.ru/kassir/hall/view/24213'),
(41, 'Театр им. М.Н.Ермоловой', 'КАССИР.РУ предлагает вам ознакомиться с афишей Театра Ермоловой и купить билеты на любое представление в режиме онлайн. Простой и интуитивно понятный интерфейс позволяет провести все необходимые операции за пару минут.\r\nТеатр Ермоловой был основан в 1925 ', 'https://msk.kassir.ru/media/poster/21f290ed1bd8a615e59f05bd79e9d1ca.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-mnermolovoy","name":"Театр им. М. Н. Ермоловой","address":"Москва, Тверская ул., 5/6', 'https://msk.kassir.ru/kassir/hall/view/290794'),
(42, 'Театр на Малой Бронной', 'ВНИМАНИЕ! На спектакли Театра на Малой Бронной за 72 часа до начала срок бронирования билетов сокращается до 15 минут!\r\nКАССИР.РУ предлагает вам ознакомиться с афишей Московского драматического театра на Малой Бронной и приобрести билеты на любой спектакл', 'https://msk.kassir.ru/media/poster/38ca8d29038207956cc47e05b0036371.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-na-maloy-bronnoy","name":"Театр на Малой Бронной - Малый зал","address":"Москва, Малая Бронная, 4', 'https://msk.kassir.ru/kassir/hall/view/306409'),
(43, 'Театр им. М.Н.Ермоловой', 'КАССИР.РУ предлагает вам ознакомиться с афишей Театра Ермоловой и купить билеты на любое представление в режиме онлайн. Простой и интуитивно понятный интерфейс позволяет провести все необходимые операции за пару минут.\r\nТеатр Ермоловой был основан в 1925 ', 'https://msk.kassir.ru/media/poster/21f290ed1bd8a615e59f05bd79e9d1ca.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-mnermolovoy","name":"Театр им. М. Н. Ермоловой","address":"Москва, Тверская ул., 5/6', 'https://msk.kassir.ru/kassir/hall/view/24217'),
(44, 'Театр им. Вл.Маяковского', 'Театру Революции – Театру Драмы – Театру им. Вл. Маяковского, как он назывался в разные годы, есть чем гордится. Имена выдающихся режиссёров, актёров, художников, творивших его историю и творящих сегодня  на его сцене, живут в памяти поколений и по праву ', 'https://msk.kassir.ru/media/poster/5c5f00a7bdb3eb084a9e800185ce5d40.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-vlmayakovskogo","name":"Театр им. Вл.Маяковского - Основная сцена","address":"г. Москва, ул. Б.Никитская,', 'https://msk.kassir.ru/kassir/hall/view/55174'),
(45, 'Театр им. Евг. Вахтангова', 'На сайте КАССИР.РУ вы всегда можете купить или забронировать билеты в Театр им. Вахтангова. Сервис доступен круглосуточно, без выходных, а оформление заказа займет всего пару минут.\r\nЛегендарный Театр им. Вахтангова неизменно входит в тройку лучших театра', 'https://msk.kassir.ru/media/poster/27429ae4ea566527ad3f52cafc0d02ae.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-evg-vahtangova","name":"Театр им. Евг. Вахтангова - Основная сцена","address":"г. Москва, ул. Арбат, д. 2', 'https://msk.kassir.ru/kassir/hall/view/307419'),
(46, 'МХТ им. А.П.Чехова', 'С момента своего основания в 1987 году МХТ им. Чехова является знаковым местом для любителей театрального искусства. Посетите этот театр с КАССИР.РУ!\r\nС 2000 года художественным руководителем является Олег Табаков. В труппе свыше 20 народных и 30 заслужен', 'https://msk.kassir.ru/media/poster/7418736dd93334f6d9fdc98eda92b02a.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/mht-im-apchehova","name":"МХТ им. А.П.Чехова - Новая сцена","address":"г. Москва, Камергерский пер., д. 3', 'https://msk.kassir.ru/kassir/hall/view/306825'),
(47, 'Театр им. Вл.Маяковского', 'Театру Революции – Театру Драмы – Театру им. Вл. Маяковского, как он назывался в разные годы, есть чем гордится. Имена выдающихся режиссёров, актёров, художников, творивших его историю и творящих сегодня  на его сцене, живут в памяти поколений и по праву ', 'https://msk.kassir.ru/media/poster/5c5f00a7bdb3eb084a9e800185ce5d40.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-vlmayakovskogo","name":"Театр им. Вл.Маяковского - Основная сцена","address":"г. Москва, ул. Б.Никитская,', 'https://msk.kassir.ru/kassir/hall/view/24220'),
(48, 'Театр им. Вл.Маяковского', 'Театру Революции – Театру Драмы – Театру им. Вл. Маяковского, как он назывался в разные годы, есть чем гордится. Имена выдающихся режиссёров, актёров, художников, творивших его историю и творящих сегодня  на его сцене, живут в памяти поколений и по праву ', 'https://msk.kassir.ru/media/poster/5c5f00a7bdb3eb084a9e800185ce5d40.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/teatry/teatr-im-vlmayakovskogo","name":"Театр им. Вл.Маяковского - Основная сцена","address":"г. Москва, ул. Б.Никитская,', 'https://msk.kassir.ru/kassir/hall/view/81486'),
(49, 'Московский международный Дом музыки (ММДМ)', 'var eventsData = {&quot;14.02.2017&quot;:[{&quot;id&quot;:52902,&quot;url&quot;:&quot;/kassir/event/view/52902&quot;,&quot;title&quot;:&quot;JAZZVALENTINE u0421u0435u0440u0433u0435u0439 u0416u0438u043bu0438u043d &amp; u0424u043eu043du043eu0433u0440u0430u0', 'https://msk.kassir.ru/media/poster/316194973b8e6e901c306f0e867e2b9d.jpg","location":{"@type":"Place","url":"https://msk.kassir.ru:443/koncertnye-zaly/moskovskiy-mejdunarodnyiy-dom-muzyiki-mmdm","name":"Московский международный Дом музыки (Светлановский за', 'https://msk.kassir.ru/kassir/hall/view/290173');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
